server:
  port : 8080

spring :
  application :
    name : test
  data :
    mongodb:
      uri : ${MONGODB_URI}
      database : ${MONGODB_DATABASE}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

springdoc:
  packages-to-scan: com.org.proddaturiMinApp.controller

