server:
  port : 8081


spring :
  application :
    name : test
  data :
    mongodb:
      uri : mongodb+srv://Manish:Suvarna@cluster.f2upph3.mongodb.net/?retryWrites=true&w=majority&appName=Cluster
      database : test



#spring.application.name=test
#spring.data.mongodb.uri=mongodb+srv://Manish:Suvarna@cluster.f2upph3.mongodb.net/?retryWrites=true&w=majority&appName=Cluster
#spring.data.mongodb.database=test
#server.port=8080